
CREATE TABLE IF NOT EXISTS user_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     username VARCHAR(255),
     password VARCHAR(255)
);



CREATE TABLE IF NOT EXISTS section_entity (
    section VARCHAR(255) NOT NULL,
    CONSTRAINT pk_section PRIMARY KEY (section)
);

CREATE TABLE IF NOT EXISTS section_skills (
    section_id VARCHAR(255) NOT NULL,
    skills VARCHAR(255) NOT NULL,
    CONSTRAINT pk_section_skills PRIMARY KEY (section_id, skills),
    CONSTRAINT fk_section_skills FOREIGN KEY (section_id) REFERENCES section_entity(section) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS store_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS worker_entity (
    dni VARCHAR(20) NOT NULL,
    name VARCHAR(255),
    last_names VARCHAR(255),
    max_hours INT NOT NULL DEFAULT 0,
    assigned_hours INT NOT NULL DEFAULT 0,
    id_store BIGINT,
    CONSTRAINT pk_worker PRIMARY KEY (dni),
    CONSTRAINT fk_worker_store 
        FOREIGN KEY (id_store) 
        REFERENCES store_entity (id) 
        ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS sections_workers (
    worker_dni VARCHAR(20) NOT NULL,
    section VARCHAR(255) NOT NULL,
    hours INT NOT NULL DEFAULT 0, 
    CONSTRAINT pk_sections_workers PRIMARY KEY (worker_dni, section),
    CONSTRAINT fk_worker_sections 
        FOREIGN KEY (worker_dni) 
        REFERENCES worker_entity (worker_dni) 
        ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS worker_day_storage_entity (
    dni VARCHAR(20) NOT NULL,
    name VARCHAR(255),
    last_names VARCHAR(255),
    max_hours INT NOT NULL DEFAULT 0,
    assigned_hours INT NOT NULL DEFAULT 0,
    id_store BIGINT,
    CONSTRAINT pk_worker PRIMARY KEY (dni),
    CONSTRAINT fk_worker_store 
        FOREIGN KEY (id_store) 
        REFERENCES store_entity (id) 
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sections_storage_workers (
    dni VARCHAR(20) NOT NULL,
    section VARCHAR(255) NOT NULL,
    hours INT NOT NULL DEFAULT 0, 
    CONSTRAINT pk_sections_storage_workers PRIMARY KEY (dni, section),
    CONSTRAINT fk_worker_sections 
        FOREIGN KEY (dni) 
        REFERENCES worker_day_storage_entity (dni) 
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS section_work_day_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id VARCHAR(255),
    assigned_hours INT,
    required_hours INT,
    CONSTRAINT pk_section_work_day PRIMARY KEY (id),
    CONSTRAINT fk_workday_section 
        FOREIGN KEY (section_id) 
        REFERENCES section_entity (section)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS store_work_day_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    id_store BIGINT,
    CONSTRAINT pk_store_workday PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS store_work_day_entity_list_sections (
    store_work_day_entity_id BIGINT NOT NULL,
    list_sections_id BIGINT NOT NULL,
    CONSTRAINT uk_list_sections UNIQUE (list_sections_id),
    CONSTRAINT fk_store_workday_rel 
        FOREIGN KEY (store_work_day_entity_id) 
        REFERENCES store_work_day_entity (id),
    CONSTRAINT fk_section_workday_rel 
        FOREIGN KEY (list_sections_id) 
        REFERENCES section_work_day_entity (id)
);
